### ISSUE TITLE
GKE with Python example outputs issue

### ISSUE THREAD

**Issue by Lawouach** [pulumi/examples#278]
Hey,

The example at https://github.com/pulumi/examples/blob/master/gcp-py-gke/__main__.py
will output the Kube config as follows:

```yaml
$ pulumi stack output kubeconfig
apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: <pulumi.output.Output object at 0x7f52f1058d68>
        server: https://35....
    name: myproject_europe-west1-b_k8s-cluster-0ee310e
    contexts:
    - context:
        cluster: myproject_europe-west1-b_k8s-cluster-0ee310e
        user: myproject_europe-west1-b_k8s-cluster-0ee310e
    name: myproject_europe-west1-b_k8s-cluster-0ee310e
    current-context: myproject_europe-west1-b_k8s-cluster-0ee310e
    kind: Config
    preferences: {}
    users:
    - name: myproject_europe-west1-b_k8s-cluster-0ee310e
    user:
        auth-provider:
        config:
            cmd-args: config config-helper --format=json
            cmd-path: gcloud
            expiry-key: '{.credential.token_expiry}'
            token-key: '{.credential.access_token}'
        name: gcp
```

Notice the `certificate-authority-data` is not the actual certificate string. Is that expected?
